#!/usr/bin/python
# This script crops oommf-generated bmp images
# 1. Crop images using ImageMagick
# 2. bmp2avi.py Convert cropped images into a video
# Usage:
# TODO:
# - 
import subprocess
import os

# Crop oommf-generated/converted bmp images
print "Crop oommf-generated/converted bmp images"
subprocess.call("batchcrop.py", shell=True)

# change to the cropped directory (generated by batchcrop.py)
os.chdir('./cropped')
	
# convert cropped bmpfiles to avi with bmp2avi.py
print "Convert cropped bitmap images to a video"
subprocess.call("bmp2avi.py", shell=True)